server:
  servlet:
    contextPath: /CUSTOMER_API
  port: 8080
kai:
  name: CUSTOMER_API
  key: custinfoq51klfoni1ezxl5f2ckpfx671
  threadName: CUSTOMER_API
  pollSize: 100
  error:
    code996: "Error insert request to DB#{0}"
    code997: "Cannot be processed"
    code998: "Timeout {0}"
    code999: "Internal Server Error {0}"
    code801: "Request type not valid"
    code802: "Problem with calculating timeout or sendtime in request type 'response'"
    code803: "RequestId not exist"
    code804: "Request lacks valid information: {0}"
    code805: "Problem with command in request type 'request'"
    code700: "API key not exists"
    code701: "API not exist"
    code600: "Problem in mapper object"
    code501: "Failed to insert to the database#{0}"
    code502: "Failed to update to the database#{0}"
    code503: "Failed to read from the database#{0}"
    code504: "Failed to delete from the database#{0}"
    code505: "Failed to call api#{0}"
    code333: "Don't have method validate for AuthenType"
spring:
  application:
    name: KAIASIA_CUSTOMER
  config:
    import: optional:file:application.yml
  database:
    postgres: true
  redis:
    host: 14.225.254.212
    port: 6379
    timeout: 5000
  postgredatasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://14.225.254.212:5432/KAI_API?currentSchema=customerinfo_api
    username: custinfo_api
    password: custinfo@kaiasia
    maximum-pool-size: 50
    idleTimeout: 120000
    minimumIdle: 10
  jpa:
    show-sql: false
    open-in-view: false

dbinfo:
  apiRequest: request_in
  apiResponse: request_out
dep-api:
  auth-api:
    apiName: AUTH_API
    url: http://localhost:8059/AUTH_API/process
    timeout: 60000
    apiKey: authq51klfoni1ezxl5f2ckpfx248
    authenType:
      auth-1: takeSession
      auth-3: confirmOTP
  t24utils-api:
    apiName: T24_UTIL_API
    url: http://14.225.254.212:8082/T24_UTIL_API/process
    timeout: 60000
    apiKey: VDI0X1VUSUxfQVBJ
    authenType:
      fundtransfer: KAI.API.FT.PROCESS
      login: KAI.API.GET.LOGIN
  t24utilsApi:
    apiName: T24_UTIL_API
    url: http://14.225.254.212:8082/T24_UTIL_API/process
    timeout: 60000
    apiKey: VDI0X1VUSUxfQVBJ
#logging:
#  file:
#    name: erro.log
#  level:
#    root: error